version: "3.9"

services:
  postgres-test:
    container_name: 'postgres-test'
    image: postgres:17
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command:
      - "postgres"
      - "-c"
      - "port=${POSTGRES_PORT}"
    networks:
      - test-internal

volumes:
  test-postgres-data:

networks:
  test-internal:
    driver: bridge