version: "3.9"

services:
  pr-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      REST_PORT: "${REST_PORT}"
      REST_HOST: "${REST_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      METRICS_PORT: "${METRICS_PORT}"

    volumes:
      - pr-service-logs:/app/logs
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${METRICS_PORT}:${METRICS_PORT}"
    networks:
      - internal

  postgres:
    container_name: 'postgres'
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command:
      - "postgres"
      - "-c"
      - "port=${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:${PROMETHEUS_PORT}/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./infra/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./infra/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./infra/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    networks:
      - internal
    depends_on:
      prometheus:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      DS_PROMETHEUS: "${DS_PROMETHEUS}"

volumes:
  postgres-data:
  grafana-storage:
  pr-service-logs:

networks:
  internal:
    driver: bridge