global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'pr-service'
    static_configs:
      - targets: ['pr-service:9000']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
