server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pr-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pr-service
          __path__: /var/log/pr-service.log

    pipeline_stages:
      - json:
          expressions:
            level: level
            layer: layer
            table: table
            span_id: span_id

      - labels:
          level:
          layer:
          table:
          span_id:
